#! /bin/bash

# Last edited by Peter Mwesigwa on June 11 2014.

# Prints the users name using a printf statement

inputname=$1

printf "Your name is %s\n" $inputname

n=$2

for ((c=1; c<n; c++))
do
    printf "Counting %i\n" $c
done

